title: Arun Kumar | Portfolio
email: kumararun97429@gmail.com
description: Arun Kumar - Software Developer & AI Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carbonFibreCode.github.io"
twitter_username: no_arun_
github_username:  carbonFibreCode

plugins:
  - jekyll-feed
